apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnet-router
  namespace: tailscale
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: "tailscale"
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        env:
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: AUTH_KEY
              optional: true
        - name: TS_ROUTES
          value: "10.42.0.0/16,10.43.0.0/16,10.44.0.0/16"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
