apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: carikatla
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cocatrip@yahoo.com
    privateKeySecretRef:
      name: account-key-staging
    solvers:
    - http01:
        ingress:
          class:  nginx
